---
- name: Prepare the Minecraft Server!
  hosts: all
  sudo: yes

  tasks:

  - name: Update the Minecrat Server - Packages to latest version
    apt: upgrade=dist update_cache=yes

  - name: Install openjdk-7-jdk
    apt: pkg=openjdk-7-jre state=installed update_cache=true
    
  - name: Install screen
    apt: name=screen state=present
    
  - name: Install git
    apt: name=git state=present
    
  - name: Install fail2ban
    apt: name=fail2ban state=present

  - name: Copy fail2ban
    copy: src=/etc/fail2ban/jail.conf dest=/etc/fail2ban/jail.local remote_src=true

  - name: Update fail2ban policy
    lineinfile: dest=/etc/fail2ban/jail.local regexp="^bantime  = 600$" line="bantime  = 20000"
    
  - name: Restart fail2ban
    service: name=fail2ban state=restarted

  - name: Reboot server
    command: /sbin/reboot
